### ISSUE TITLE
디스코드 RPC 직접 구현하기

### ISSUE THREAD

**Issue by minibox24** [wakmusic/wakmusic-pc#141]
![image](https://github.com/wakmusic/wakmusic-pc/assets/61264156/412e4484-c64d-44fd-a0c2-872817427eee)
![image](https://github.com/wakmusic/wakmusic-pc/assets/61264156/ff369f61-36c3-412f-bfe7-cc6b629e5e9b)

극도의 경량화를 진행했음에도 불구하고 한낱 discord-api-types 라이브러리 따위가 혼자 2mb를 먹고 있음.

추후에 셀프로 디코 RPC를 구현하여서 조금이라도 더 용량 줄이기

**Comment by chuhyeonjin** [comment]
[@xhayper/discord-rpc](https://github.com/xhayper/discord-rpc#xhayperdiscord-rpc) 1.0.24 버전에서 discord-api-types가 devDependencies로 옮겨져 이제는 번들에 포함되지 않게되었습니다.

**Comment by minibox24** [comment]
> [@xhayper/discord-rpc](https://github.com/xhayper/discord-rpc#xhayperdiscord-rpc) 1.0.24 버전에서 discord-api-types가 devDependencies로 옮겨져 이제는 번들에 포함되지 않게 되었습니다.

직접 RPC 라이브러리를 구현할 생각만 하고 있었지 직접 PR을 넣을 생각은 하나도 못하고 있었네요..ㅋㅋㅋ

도움 주셔서 감사합니다!
1.0.4 버전부터 더 작아진 asar 파일로 배포될 예정입니다
