### ISSUE TITLE
의외로 많은 글씨들의 색이 똑바로 정해져 있지 않음

### ISSUE THREAD

**Issue by minibox24** [wakmusic/wakmusic-pc#32]
### 작업 내용

![image](https://github.com/wakmusic/wakmusic-pc/assets/61264156/7fa9d64e-1ce6-4575-8e91-c506e9966886)

![image](https://github.com/wakmusic/wakmusic-pc/assets/61264156/1c5e69c0-bef0-46d2-bd77-2b98f8102f0d)

검정색같지만 검정색이 아닌 텍스트들 적폐 처단하기

**Comment by kimbuckgur** [comment]
홀리몰리
