### ISSUE TITLE
macOS의 미디어 컨트롤러에서 seek이 안되는 현상

### ISSUE THREAD

**Issue by opentypefont** [wakmusic/wakmusic-pc#81]
api/lyrics 브랜치에서 노래를 재생했을 때 일시정지/곡 넘기기 기능은 정상작동하나 seek 기능이 작동하지 않습니다.

**Comment by minibox24** [comment]
https://github.com/wakmusic/wakmusic-pc/pull/79/commits/424910441e38d2300b9d7ad4bae7084333ec8b76 에서 수정 완료

제보 감사드립니다
